spring.application.name=demo
tmdb.api.base-url=https://api.themoviedb.org/3
tmdb.api.access-token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzZDIwNTQ0ZjA2YWUzMjY4NTU2YWJkYzYzOTRiYWVjNiIsIm5iZiI6MTczNjI1MjcwOS42NzkwMDAxLCJzdWIiOiI2NzdkMWQyNTE1Y2FmZThhYWQ3NGFmMWEiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.Hy_sqkTyrwFG5z0VVcOcwn4ra2KHMrEbZ3pxUgxA9FY

# MySQL Database 설정
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ottdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=ottuser
spring.datasource.password=ottpassword

# JPA & Hibernate 설정
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Config
jwt.secret=v8y/B?E(H+MbQeThWmYq3t6w9z$C&F)J@NcRfUjXn2r5u8x/A?D*G-KaPdSgVkYp
jwt.expiration=86400000