spring.application.name=demo
tmdb.api.base-url=https://api.themoviedb.org/3
tmdb.api.access-token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzZDIwNTQ0ZjA2YWUzMjY4NTU2YWJkYzYzOTRiYWVjNiIsIm5iZiI6MTczNjI1MjcwOS42NzkwMDAxLCJzdWIiOiI2NzdkMWQyNTE1Y2FmZThhYWQ3NGFmMWEiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.Hy_sqkTyrwFG5z0VVcOcwn4ra2KHMrEbZ3pxUgxA9FY

# H2 Database & JPA 설정
spring.datasource.url=jdbc:h2:mem:ottdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 콘솔 사용 (웹 브라우저에서 DB 확인 가능)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Spring Boot 3에서 H2 콘솔 404 및 리소스 매핑 에러 방지
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
server.contextPath=/api